"""add pament type and number of installments to expenses

Revision ID: 5b98f2c4d0f3
Revises: ba655664e305
Create Date: 2026-08-27 21:14:16.563124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b98f2c4d0f3'
down_revision = 'ba655664e305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('number_of_installments', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('number_of_installments')
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###
